INSERT INTO questions (difficulty, category, question, correct_answer) VALUES 
('easy', 'Geography', 'What is the capital of the United States?', 'Washington, D.C.'),
('medium', 'History', 'In what year was the State of Israel founded?', '1948'),
('hard', 'Science', 'What is the chemical element with the symbol "Au"?', 'Gold'),
('easy', 'Sports', 'Which sport is played with a large orange ball?', 'Basketball'),
('medium', 'Entertainment', 'Who directed the movie "Titanic"?', 'James Cameron'),
('hard', 'Geography', 'Which country has the largest land area in the world?', 'Russia'),
('easy', 'Nature', 'What is the largest mammal in the world?', 'Blue whale'),
('medium', 'History', 'Who was the first Prime Minister of Israel?', 'David Ben-Gurion'),
('hard', 'Science', 'Which planet is known as the "Red Planet"?', 'Mars'),
('easy', 'Food', 'What is the main ingredient in hummus?', 'Chickpeas'),
('medium', 'Technology', 'Who founded Microsoft?', 'Bill Gates'),
('hard', 'Mathematics', 'What is the square root of 144?', '12'),
('easy', 'Music', 'Which famous band was known as the "Fab Four"?', 'The Beatles'),
('medium', 'Literature', 'Who wrote "1984"?', 'George Orwell'),
('hard', 'Geography', 'What is the deepest ocean in the world?', 'Pacific Ocean'),
('easy', 'Movies', 'Who is the main character in "Harry Potter"?', 'Harry Potter'),
('medium', 'Science', 'What is the chemical formula of water?', 'H2O'),
('hard', 'History', 'Who was the 16th President of the United States?', 'Abraham Lincoln'),
('easy', 'TV Shows', 'What is the name of the yellow cartoon family?', 'The Simpsons'),
('medium', 'Space', 'What is the name of the first man to walk on the moon?', 'Neil Armstrong');

INSERT INTO question_answers (question_id, answer) VALUES 
(1, 'New York'), (1, 'Los Angeles'), (1, 'Chicago'), (1, 'Washington, D.C.'),
(2, '1945'), (2, '1946'), (2, '1948'), (2, '1950'),
(3, 'Aluminum'), (3, 'Mercury'), (3, 'Gold'), (3, 'Zinc'),
(4, 'Soccer'), (4, 'Tennis'), (4, 'Basketball'), (4, 'Baseball'),
(5, 'Steven Spielberg'), (5, 'James Cameron'), (5, 'Martin Scorsese'), (5, 'Christopher Nolan'),
(6, 'Canada'), (6, 'United States'), (6, 'China'), (6, 'Russia'),
(7, 'African Elephant'), (7, 'Rhinoceros'), (7, 'Blue whale'), (7, 'Grizzly bear'),
(8, 'Golda Meir'), (8, 'Menachem Begin'), (8, 'David Ben-Gurion'), (8, 'Yitzhak Rabin'),
(9, 'Venus'), (9, 'Earth'), (9, 'Mars'), (9, 'Saturn'),
(10, 'Beans'), (10, 'Lentils'), (10, 'Chickpeas'), (10, 'Rice'),
(11, 'Steve Jobs'), (11, 'Mark Zuckerberg'), (11, 'Bill Gates'), (11, 'Elon Musk'),
(12, '10'), (12, '11'), (12, '12'), (12, '13'),
(13, 'The Rolling Stones'), (13, 'The Beatles'), (13, 'Pink Floyd'), (13, 'Queen'),
(14, 'J.K. Rowling'), (14, 'George Orwell'), (14, 'William Shakespeare'), (14, 'Mark Twain'),
(15, 'Atlantic Ocean'), (15, 'Indian Ocean'), (15, 'Pacific Ocean'), (15, 'Arctic Ocean'),
(16, 'Hermione Granger'), (16, 'Harry Potter'), (16, 'Ron Weasley'), (16, 'Draco Malfoy'),
(17, 'CO2'), (17, 'H2O'), (17, 'O2'), (17, 'NaCl'),
(18, 'George Washington'), (18, 'Abraham Lincoln'), (18, 'Thomas Jefferson'), (18, 'Theodore Roosevelt'),
(19, 'Family Guy'), (19, 'The Simpsons'), (19, 'South Park'), (19, 'Rick and Morty'),
(20, 'Buzz Aldrin'), (20, 'Neil Armstrong'), (20, 'Yuri Gagarin'), (20, 'Michael Collins');
